### ISSUE TITLE
[Fixed] 에셋 추가 부탁드립니다!

### ISSUE THREAD

**Issue by songsuyoung** [MungchiTheBlackThing/The-Black-Thing#9]
- [x] moon radio, hourglass sprite 추가(복구) 부탁드립니다!
![image](https://github.com/user-attachments/assets/25cfd356-245c-4138-92f6-9474835587ab)
- [x] 위 이미지에서 쪽지 말풍선, 그리고 쌍안경 말풍선 추가해주세요!
- [x] 달 500자 초과시 뜨는 경고문, 이미지가 아닌 텍스트로 변경
![image](https://github.com/user-attachments/assets/27404919-16e4-48f6-a129-cd378d44baec)
- [x] 달나라 송신기 Alert Popup 이상해진거 수정해주세요!
![image](https://github.com/user-attachments/assets/c8b1c3fd-50d4-41dc-aece-d8e81c647d48)
- [x] 번역팀에게 디스코드에 올린 json파일 번역 부탁드리기
- [x] 나머지 시간대(밤 제외)  아래와 같은 Prefab 작업 해주세요!
![image](https://github.com/user-attachments/assets/4af70d35-4133-4339-b2dd-f0f1eb1c3390)

**Comment by andiemaelee** [comment]
이거 제가 체크 못 하게 되어 있어서 확인하시면 체크해서 없애 주세요! 혹시 안 되거나 이상한 게 있다면 말씀해 주세요~!

**Comment by songsuyoung** [comment]
이미지 분리까지 추가 완료
